sudo: false
language: node_js

cache: npm

node_js:
  - "10"

services:
  - docker

before_install:
  - docker build -t loopback .
  - docker run -p 127.0.0.1:80:4567 -d loopback:latest
  - docker ps -a
  - docker tag loopback:latest mohamedragabessa/vehicle-backend:latest

  #  - pip install --user awscli
  # - export PATH=$PATH:$HOME/.local/bin
  # - eval $(aws ecr get-login --no-include-email --region us-east-2)
  # - docker build -t vehicles/backend .
  # - docker run -p 127.0.0.1:80:4567 -d vehicles/backend:latest
  # - docker tag vehicles/backend:latest 307045200927.dkr.ecr.us-east-2.amazonaws.com/vehicles/backend:latest

script: npm run test
install: npm install

branches:
  only:
    - master

before_deploy: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
deploy:
  provider: script
  script: docker push mohamedragabessa/vehicle-backend:latest
  on:
    branch: master
# deploy:
#   provider: script
#   script: docker push 307045200927.dkr.ecr.us-east-2.amazonaws.com/vehicles/backend:latest
#   # docker push mohamedragabessa/loopbacktravis:latest
#   on:
#     branch: master
#     # loopback:latest
